# Generated by Django 3.1.5 on 2021-03-05 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20210221_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likedislike',
            options={'verbose_name': 'Лайк/Дизлайк', 'verbose_name_plural': 'Лайки/Дизлайки'},
        ),
    ]
