# Generated by Django 3.1.5 on 2021-01-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='followers',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Кол-во подписчиков'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscribers',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Кол-во подписок'),
        ),
    ]
